### ISSUE TITLE
NCCL all_reduce_perf hangs after command 'kubectl exec' using MPIJOB

### ISSUE THREAD

**Issue by jjkobe** [NVIDIA/nccl#1564]
Hi, recently I run all_reduce_perf using MPIJOB with RMDA. But launcher‘s log **hangs** after 'kubectl exec'

nccl version：2.21.5
mpi version：2.19.3
K8S version：1.26.3
containerd version：1.6.28

This is my MPIJOB yaml:
```
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  labels:
    app: nvidia-mpi-training-sample-mpijob
    component: training
    kubemaker: nvidia-mpi-training-sample
    mandatory.k8s.alipay.com/server-owner: xxx
    meta.k8s.alipay.com/min-replicas: '3'
    meta.k8s.alipay.com/replicas: '3'
    meta.k8s.alipay.com/workload: batch
  name: nvidia-mpi-training-sample-mpijob
  namespace: kubemaker
spec:
  backoffLimit: 0
  replicas: 2
  template:
    metadata:
      labels:
        app: nvidia-mpi-training-sample-mpijob
        aliyun.com/gpu-count: "2"
        intelligent.sofastack.io/vgpu-specification: nvidia-full-a10
        component: training
        kubemaker: nvidia-mpi-training-sample
        mandatory.k8s.alipay.com/server-owner: xxx
        meta.k8s.alipay.com/min-replicas: '3'
        meta.k8s.alipay.com/replicas: '3'
        meta.k8s.alipay.com/workload: batch
      name: mpijob-nvidia
      namespace: kubemaker
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: kubemaker-user
      serviceAccount: kubemaker-user
      containers:
        - command: ["/bin/bash", "-c"]        
          args: ["mpirun -np 2 --allow-run-as-root --bind-to none --mca btl '^openib' -x NCCL_IB_DISABLE=0 -x NCCL_DEBUG=TRACE -x NCCL_DEBUG_SUBSYS=ALL -x LD_LIBRARY_PATH -x NCCL_SOCKET_IFNAME=ens4f1 -x NCCL_IB_HCA=mlx5_3 -x UCX_NET_DEVICES=mlx5_3:1 -x NCCL_TOPO_DUMP_FILE=/tmp/topo.xml -x PATH /opt/nccl-tests/build/all_reduce_perf -b 1G -e 2G -f 2 -g 1 -n 20"]
          env:
            - name: OMPI_ALLOW_RUN_AS_ROOT
              value: "1"
            - name: OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
              value: "1"
          image: "harbor.cnstack.local/library/nccl-tests:12.4.1-cudnn-devel-ubuntu20.04-nccl2.21.5-1-85f914"
          #image: harbor.cnstack.local/library/nccl-tests:12.0.1-cudnn8-devel-ubuntu20.04-nccl2.19.3-1-2ff05b2
          # imagePullPolicy: Always
          name: mpijob
          securityContext:
            capabilities:
             add: ["IPC_LOCK","NET_ADMIN"]
            # privileged: false
          resources:
            limits: 
              rdma/hca: 1
              cpu: 40
              memory: 80Gi
            requests:
              cpu: 4
              memory: 8Gi
              rdma/hca: 1
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  # TODO
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values:
                      - "node45"
                      - "node47"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      # TODO 
      tolerations:
        - key: "node.kubernetes.io/unschedulable"
          effect: "NoSchedule"
```

This is launcher pod's log，then the process hangs and no more logs. But the all_reduce_perf process is created in both worker pod.
```
+ POD_NAME=nvidia-mpi-training-sample-mpijob-worker-1
+ shift
+ /opt/kube/kubectl exec nvidia-mpi-training-sample-mpijob-worker-1 --container mpijob -- /bin/sh -c    OPAL_PREFIX=/opt/hpcx/ompi ; export OPAL_PREFIX;    PATH=/opt/hpcx/ompi/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/opt/hpcx/ompi/lib:${LD_LIBRARY_PATH:-} ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/opt/hpcx/ompi/lib:${DYLD_LIBRARY_PATH:-} ; export DYLD_LIBRARY_PATH ;   /opt/hpcx/ompi/bin/orted -mca ess "env" -mca ess_base_jobid "2715287552" -mca ess_base_vpid 2 -mca ess_base_num_procs "3" -mca orte_node_regex "nvidia-mpi-training-sample-mpijob-launcher-vg[2:28]b,nvidia-mpi-training-sample-mpijob-worker-[1:0-1]@0(3)" -mca orte_hnp_uri "2715287552.0;tcp://172.24.170.252:33960" --mca btl "^openib" -mca plm "rsh" --tree-spawn -mca routed "radix" -mca orte_parent_uri "2715287552.0;tcp://172.24.170.252:33960" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca hwloc_base_binding_policy "none" -mca pmix "^s1,s2,cray,isolated"
+ POD_NAME=nvidia-mpi-training-sample-mpijob-worker-0
+ shift
+ /opt/kube/kubectl exec nvidia-mpi-training-sample-mpijob-worker-0 --container mpijob -- /bin/sh -c    OPAL_PREFIX=/opt/hpcx/ompi ; export OPAL_PREFIX;    PATH=/opt/hpcx/ompi/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/opt/hpcx/ompi/lib:${LD_LIBRARY_PATH:-} ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/opt/hpcx/ompi/lib:${DYLD_LIBRARY_PATH:-} ; export DYLD_LIBRARY_PATH ;   /opt/hpcx/ompi/bin/orted -mca ess "env" -mca ess_base_jobid "2715287552" -mca ess_base_vpid 1 -mca ess_base_num_procs "3" -mca orte_node_regex "nvidia-mpi-training-sample-mpijob-launcher-vg[2:28]b,nvidia-mpi-training-sample-mpijob-worker-[1:0-1]@0(3)" -mca orte_hnp_uri "2715287552.0;tcp://172.24.170.252:33960" --mca btl "^openib" -mca plm "rsh" --tree-spawn -mca routed "radix" -mca orte_parent_uri "2715287552.0;tcp://172.24.170.252:33960" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca hwloc_base_binding_policy "none" -mca pmix "^s1,s2,cray,isolated"

```

This is the environment in worker0 pod:
nvidia-smi
```
Mon Jan  6 09:46:11 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  Off  | 00000000:1F:00.0 Off |                    0 |
| N/A   35C    P0    48W / 250W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-PCI...  Off  | 00000000:20:00.0 Off |                    0 |
| N/A   35C    P0    46W / 250W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

ibv_devices
```
    device          	   node GUID
    ------          	----------------
    mlx5_3          	946dae0300f61e0f

```

ibstat
```
CA 'mlx5_0'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f62586
	System image GUID: 0x946dae0300f62586
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef62586
		Link layer: Ethernet
CA 'mlx5_1'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f62587
	System image GUID: 0x946dae0300f62586
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef62587
		Link layer: Ethernet
CA 'mlx5_2'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f61e0e
	System image GUID: 0x946dae0300f61e0e
	Port 1:
		State: Active
		Physical state: LinkUp
		Rate: 100
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef61e0e
		Link layer: Ethernet
CA 'mlx5_3'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f61e0f
	System image GUID: 0x946dae0300f61e0e
	Port 1:
		State: Active
		Physical state: LinkUp
		Rate: 100
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef61e0f
		Link layer: Ethernet
CA 'mlx5_4'
	CA type: MT4125
	Number of ports: 1
	Firmware version: 22.31.1014
	Hardware version: 0
	Node GUID: 0x08c0eb03009165ee
	System image GUID: 0x08c0eb03009165ee
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x0ac0ebfffe9165ee
		Link layer: Ethernet
CA 'mlx5_5'
	CA type: MT4125
	Number of ports: 1
	Firmware version: 22.31.1014
	Hardware version: 0
	Node GUID: 0x08c0eb03009165ef
	System image GUID: 0x08c0eb03009165ee
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x0ac0ebfffe9165ef
		Link layer: Ethernet
CA 'mlx5_6'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f626fe
	System image GUID: 0x946dae0300f626fe
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef626fe
		Link layer: Ethernet
CA 'mlx5_7'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f626ff
	System image GUID: 0x946dae0300f626fe
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef626ff
		Link layer: Ethernet

```

This is the environment in worker1 pod:
nvidia-smi
```
Mon Jan  6 09:48:06 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  Off  | 00000000:0C:00.0 Off |                  N/A |
| N/A   34C    P0    46W / 250W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-PCI...  Off  | 00000000:0D:00.0 Off |                    0 |
| N/A   33C    P0    44W / 250W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

ibv_devices
```
    device          	   node GUID
    ------          	----------------
    mlx5_3          	946dae0300f62507

```

ibstat
```
CA 'mlx5_0'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f6225e
	System image GUID: 0x946dae0300f6225e
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef6225e
		Link layer: Ethernet
CA 'mlx5_1'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f6225f
	System image GUID: 0x946dae0300f6225e
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef6225f
		Link layer: Ethernet
CA 'mlx5_2'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f62506
	System image GUID: 0x946dae0300f62506
	Port 1:
		State: Active
		Physical state: LinkUp
		Rate: 100
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef62506
		Link layer: Ethernet
CA 'mlx5_3'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f62507
	System image GUID: 0x946dae0300f62506
	Port 1:
		State: Active
		Physical state: LinkUp
		Rate: 100
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef62507
		Link layer: Ethernet
CA 'mlx5_4'
	CA type: MT4125
	Number of ports: 1
	Firmware version: 22.31.1014
	Hardware version: 0
	Node GUID: 0x08c0eb030091951c
	System image GUID: 0x08c0eb030091951c
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x0ac0ebfffe91951c
		Link layer: Ethernet
CA 'mlx5_5'
	CA type: MT4125
	Number of ports: 1
	Firmware version: 22.31.1014
	Hardware version: 0
	Node GUID: 0x08c0eb030091951d
	System image GUID: 0x08c0eb030091951c
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x0ac0ebfffe91951d
		Link layer: Ethernet
CA 'mlx5_6'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f62036
	System image GUID: 0x946dae0300f62036
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef62036
		Link layer: Ethernet
CA 'mlx5_7'
	CA type: MT4123
	Number of ports: 1
	Firmware version: 20.35.3006
	Hardware version: 0
	Node GUID: 0x946dae0300f62037
	System image GUID: 0x946dae0300f62036
	Port 1:
		State: Down
		Physical state: Disabled
		Rate: 40
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x00010000
		Port GUID: 0x966daefffef62037
		Link layer: Ethernet

```

ib_send_bw test shows:
```
root@node45:/opt/nccl-tests# ib_send_bw -a -c UD -d mlx5_3 -i 1

************************************
* Waiting for client to connect... *
************************************
 Max msg size in UD is MTU 4096
 Changing to this MTU
---------------------------------------------------------------------------------------
                    Send BW Test
 Dual-port       : OFF          Device         : mlx5_3
 Number of qps   : 1            Transport type : IB
 Connection type : UD           Using SRQ      : OFF
 PCIe relax order: ON
 ibv_wr* API     : ON
 RX depth        : 1000
 CQ Moderation   : 100
 Mtu             : 4096[B]
 Link type       : Ethernet
 GID index       : 3
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x2bea PSN 0xfb13f6
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:172:100:27:185
 remote address: LID 0000 QPN 0x2c86 PSN 0xa84a8c
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:172:100:27:177
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]       BW min[MB/sec]
Conflicting CPU frequency values detected: 799.975000 != 3500.000000. CPU Frequency is not max.
 2          1000             0.00               9.95               5.214125               0.00   
Conflicting CPU frequency values detected: 799.975000 != 3500.000000. CPU Frequency is not max.
 4          1000             0.00               25.39              6.655585               0.00   
Conflicting CPU frequency values detected: 799.975000 != 3499.829000. CPU Frequency is not max.
 8          1000             0.00               51.57              6.759999               0.00   
Conflicting CPU frequency values detected: 799.975000 != 3500.000000. CPU Frequency is not max.
 16         1000             0.00               57.85              3.790971               0.00   
Conflicting CPU frequency values detected: 799.975000 != 3500.000000. CPU Frequency is not max.
 32         1000             0.00               117.83             3.860970               0.00   
Conflicting CPU frequency values detected: 799.975000 != 3500.000000. CPU Frequency is not max.
 64         1000             0.00               431.14             7.063857               0.00   
Conflicting CPU frequency values detected: 799.975000 != 3500.000000. CPU Frequency is not max.
 128        1000             0.00               829.54             6.795579               0.00   
Conflicting CPU frequency values detected: 799.975000 != 3500.000000. CPU Frequency is not max.
 256        1000             0.00               1734.32            7.103755               0.00   
Conflicting CPU frequency values detected: 802.709000 != 3500.000000. CPU Frequency is not max.
 512        1000             0.00               3433.34            7.031480               0.00   
Conflicting CPU frequency values detected: 799.975000 != 3500.000000. CPU Frequency is not max.
 1024       1000             0.00               6538.18            6.695097               0.00   
Conflicting CPU frequency values detected: 799.975000 != 3500.000000. CPU Frequency is not max.
 2048       1000             0.00               11350.69                   5.811553               0.00   
Conflicting CPU frequency values detected: 799.975000 != 3500.000000. CPU Frequency is not max.
 4096       1000             0.00               11635.88                   2.978784               0.00   
---------------------------------------------------------------------------------------
root@node45:/opt/nccl-tests# 

```

Do you have any idea?
