### ISSUE TITLE
Kubeflow - NCCL version 2.9.6+cuda11.0 -- NCCL WARN Call to posix_fallocate failed : No space left on device

### ISSUE THREAD

**Issue by tboquet** [NVIDIA/nccl#525]
Hello, I suddenly had this error but everything was working fine 3 days ago when training a model on multiple GPUs.

I am launching my jobs using kubeflow, I am using the latest `gcr.io/deeplearning-platform-release/tf2-gpu.2-4:m69` image and the kubernetes node has 4 T4 GPUs.

```
[3] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
[3] NCCL INFO include/shm.h:41 -> 2
[3] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-1462445a6f01cbfc-1-2-3 (size 9637888)
```
Any idea on how to solve this problem in kubernetes or bypass it without any performance loss?
I have found some documentation on the error but I am not sure what is the best option:
 - #342 
 - #290 
 - a solution on the kubernetes side (override the 64mb allocated by docker by mounting a volume in memory):
 ```
spec:
  volumes:
  - name: dshm
    emptyDir:     
        medium: Memory
  containers:
  - image:  image-name
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
```

Notes: setting `NCCL_SHM_DISABLE=1` works. Using a `a2-highgpu-8g` instance works with 8 gpus without any shared memory error.
